std::cout << "Sure, Why Not?\n";
std::cout << "This is a sampe for C++.\n";
int Sample;
Sample = 500;
int C++ = 10;
int Hello;
Hello = 800 * 200;
std::cout << Hello << "\n";
int Money = 1;
std::cout << "Enter Money Amount";
std::cin >> Money;
